version: '3'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    depends_on: 
      - prometheus
    


  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    user: root
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
    - ms-java-prom
    - ms-go-prom


  ms-go-prom:
    build: ./application/ms-go-prometheus
    container_name: ms-go-prom
    ports:
      - 8881:8881
 
  ms-java-prom:
    build: ./application/ms-java-prometheus
    container_name: ms-java-prom
    ports:
      - 8084:8084


      

 
